---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd daemon

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true
  listen: Restart kubelet
